worflow updates

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -39,12 +39,10 @@ jobs:
             jq --arg pr_number "$pr_number" '.version = ($pr_number | tonumber)' "$file" > tmp.$$.json && mv tmp.$$.json "$file"
           done
 
-      - name: Run dc-template-linter
+      - name: Run dc-template-linter with debug
         run: |
           export GOPATH=$(go env GOPATH)
-          for file in $(git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.json$'); do
-            $GOPATH/bin/dc-template-linter -cloudflare -inplace -loglevel error "$file"
-          done
+          $GOPATH/bin/dc-template-linter -inplace -loglevel debug *.json || echo "Linting failed with exit code $?"
 
       - name: Check for changes
         id: check_changes
